#!/usr/bin/env zsh

read -p "Personal Box? (Y/N): " confirm 


echo "stow zsh"
stow zsh
echo "stow tmux"
stow tmux
echo "stow neovim"
stow neovim
echo "stow hammerspoon"
stow hammerspoon
# echo "stow vscode"
# stow --target="~/Library/Application Support/Code/User/" vscode

if [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]]; then
	echo "stow git"
	stow git
fi


