#!/usr/bin/env zsh

echo "stow zsh"
stow zsh
echo "stow tmux"
stow tmux
echo "stow neovim"
stow neovim
echo "stow hammerspoon"
stow hammerspoon
echo "stow wezterm"
stow wezterm
echo "stow scripts"
stow scripts
# echo "stow vscode"
# stow --target="~/Library/Application Support/Code/User/" vscode
